# Generated by Django 4.2.16 on 2024-09-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_legacy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
