# Generated by Django 4.2.16 on 2024-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
